<a href="https://colab.research.google.com/github/brenosyperrek/python_pandas/blob/main/Aula_Extra_Formas_de_Sele%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = [(1, 2, 3, 4),
        (5, 6, 7, 8),
        (9, 10, 11, 12),
        (13, 14, 15, 16)]
df = pd.DataFrame(data, 'l1 l2 l3 l4'.split(), 'c1 c2 c3 c4'.split())

In [3]:
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   9  10  11  12
l4  13  14  15  16

In [4]:
df['c1']

l1     1
l2     5
l3     9
l4    13
Name: c1, dtype: int64

In [6]:
type(df['c1'])

pandas.core.series.Series

In [7]:
df[['c3', 'c1']]

    c3  c1
l1   3   1
l2   7   5
l3  11   9
l4  15  13

In [8]:
type(df[['c3', 'c1']])

pandas.core.frame.DataFrame

In [10]:
df[:]

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   9  10  11  12
l4  13  14  15  16

In [12]:
df[1:3]

    c1  c2  c3  c4
l2   5   6   7   8
l3   9  10  11  12

In [13]:
df[1:][['c3', 'c1']]

    c3  c1
l2   7   5
l3  11   9
l4  15  13

In [14]:
df.loc['l3']

c1     9
c2    10
c3    11
c4    12
Name: l3, dtype: int64

In [15]:
df.loc[['l3', 'l2']]

    c1  c2  c3  c4
l3   9  10  11  12
l2   5   6   7   8

In [16]:
df.loc['l1', 'c2']

2

In [17]:
df.iloc[0,1]

2

In [19]:
df.loc[['l3', 'l1'],['c4', 'c1']]

    c4  c1
l3  12   9
l1   4   1

In [20]:
df.iloc[[2, 0],[3, 0]]

    c4  c1
l3  12   9
l1   4   1